// Kernel-side anti-aliased font renderer.
//
// Mirrors lib/font_atlas.zig (same .bin format, generated by
// tools/build_atlas.py from a TTF). Differences:
//   - Renders directly into the gfx framebuffer (no Canvas abstraction;
//     the lib/ Canvas struct is user-space only).
//   - Embeds binaries from src/ui/assets/ so the kernel module's
//     @embedFile path resolution works (root = `src/`). The .bin files
//     are mirrored from lib/assets/ — re-run tools/build_atlas.py and
//     `cp lib/assets/*.bin src/ui/assets/` to refresh.
//
// Used by debug/panic_screen.zig for prettier crash UI. Safe to call from
// panic context: no allocation, no recursion into anything that might
// re-panic, single mutable state is the lazy-init flag (idempotent).

const std = @import("std");
const gfx = @import("gfx.zig");

pub const Glyph = extern struct {
    ax: i8, // horizontal advance
    bx: i8, // bearing x (offset from pen origin)
    by: i8, // glyph top in cell (pixels from cell top)
    w: u8,
    h: u8,
    _pad0: u8,
    atlas_x: u16,
    atlas_y: u16,
    _pad1: u16,
};

comptime {
    if (@sizeOf(Glyph) != 12) @compileError("Glyph must match build_atlas.py 12-byte layout");
}

pub const Atlas = struct {
    size_px: u8,
    baseline: u8,
    line_height: u8,
    glyph_count: u16,
    codept_start: u16,
    atlas_w: u16,
    atlas_h: u16,
    /// align(1) — the embedded blob has no special alignment guarantees.
    glyphs: [*]align(1) const Glyph,
    pixels: [*]const u8,

    pub fn parse(blob: []const u8) Atlas {
        const size_px = blob[4];
        const baseline = blob[6];
        const line_height = blob[7];
        const glyph_count = std.mem.readInt(u16, blob[8..10], .little);
        const codept_start = std.mem.readInt(u16, blob[10..12], .little);
        const atlas_w = std.mem.readInt(u16, blob[12..14], .little);
        const atlas_h = std.mem.readInt(u16, blob[14..16], .little);

        const header_size: usize = 16;
        const glyphs_size: usize = @as(usize, glyph_count) * @sizeOf(Glyph);
        const glyphs_ptr: [*]align(1) const Glyph = @ptrCast(blob.ptr + header_size);
        const pixels_ptr: [*]const u8 = blob.ptr + header_size + glyphs_size;

        return .{
            .size_px = size_px,
            .baseline = baseline,
            .line_height = line_height,
            .glyph_count = glyph_count,
            .codept_start = codept_start,
            .atlas_w = atlas_w,
            .atlas_h = atlas_h,
            .glyphs = glyphs_ptr,
            .pixels = pixels_ptr,
        };
    }

    pub fn measure(self: Atlas, text: []const u8) u32 {
        var w: u32 = 0;
        for (text) |c| {
            if (c < self.codept_start) {
                if (c == ' ') {
                    const idx: u32 = @as(u32, ' ') - self.codept_start;
                    if (idx < self.glyph_count) {
                        w += @as(u32, @intCast(self.glyphs[idx].ax));
                    }
                }
                continue;
            }
            const idx: u32 = @as(u32, c) - self.codept_start;
            if (idx >= self.glyph_count) {
                w += self.size_px / 2;
                continue;
            }
            w += @as(u32, @intCast(self.glyphs[idx].ax));
        }
        return w;
    }
};

const blob_16: []const u8 align(2) = @embedFile("assets/font_16.bin");
const blob_24: []const u8 align(2) = @embedFile("assets/font_24.bin");
const blob_mono: []const u8 align(2) = @embedFile("assets/font_mono.bin");

comptime {
    if (blob_16.len < 32) @compileError("aa_font: font_16.bin missing or truncated");
    if (blob_24.len < 32) @compileError("aa_font: font_24.bin missing or truncated");
    if (blob_mono.len < 32) @compileError("aa_font: font_mono.bin missing or truncated");
    // Validate magic bytes "ATLF" (0x464C5441 little-endian = 0x41 0x54 0x4C 0x46).
    if (blob_16[0] != 0x41 or blob_16[1] != 0x54 or blob_16[2] != 0x4C or blob_16[3] != 0x46)
        @compileError("aa_font: font_16.bin bad magic");
    if (blob_24[0] != 0x41 or blob_24[1] != 0x54 or blob_24[2] != 0x4C or blob_24[3] != 0x46)
        @compileError("aa_font: font_24.bin bad magic");
    if (blob_mono[0] != 0x41 or blob_mono[1] != 0x54 or blob_mono[2] != 0x4C or blob_mono[3] != 0x46)
        @compileError("aa_font: font_mono.bin bad magic");
}

var default_16: Atlas = undefined;
var default_24: Atlas = undefined;
var default_mono: Atlas = undefined;
var initialized: bool = false;

pub fn ensureLoaded() void {
    if (initialized) return;
    default_16 = Atlas.parse(blob_16);
    default_24 = Atlas.parse(blob_24);
    default_mono = Atlas.parse(blob_mono);
    initialized = true;
}

pub fn getDefault16() *const Atlas {
    ensureLoaded();
    return &default_16;
}

pub fn getDefault24() *const Atlas {
    ensureLoaded();
    return &default_24;
}

pub fn getDefaultMono() *const Atlas {
    ensureLoaded();
    return &default_mono;
}

/// Render `text` at `(x, y)` with `color`'s RGB and per-glyph alpha
/// coverage. `(x, y)` is the top-left of the glyph cell — `y + line_height`
/// is the next baseline. No clipping; rejects out-of-bounds pixels.
pub fn drawText(x: i32, y: i32, text: []const u8, color: u32, atlas: *const Atlas) void {
    var pen_x: i32 = x;
    for (text) |c| {
        if (c < atlas.codept_start) {
            if (c == ' ') {
                const space_idx: u32 = @as(u32, ' ') - atlas.codept_start;
                if (space_idx < atlas.glyph_count) {
                    pen_x += atlas.glyphs[space_idx].ax;
                }
            }
            continue;
        }
        const idx: u32 = @as(u32, c) - atlas.codept_start;
        if (idx >= atlas.glyph_count) {
            pen_x += @as(i32, atlas.size_px / 2);
            continue;
        }
        const g = atlas.glyphs[idx];
        const glyph_top: i32 = y + g.by;
        const glyph_left: i32 = pen_x + g.bx;
        var gy: u32 = 0;
        while (gy < g.h) : (gy += 1) {
            const py = glyph_top + @as(i32, @intCast(gy));
            const row_in_atlas: u32 = @as(u32, g.atlas_y) + gy;
            const row_off: usize = @as(usize, row_in_atlas) * atlas.atlas_w;
            var gx: u32 = 0;
            while (gx < g.w) : (gx += 1) {
                const px = glyph_left + @as(i32, @intCast(gx));
                const a = atlas.pixels[row_off + g.atlas_x + gx];
                if (a == 0) continue;
                blendPx(px, py, color, a);
            }
        }
        pen_x += g.ax;
    }
}

/// Centered variant — measures the run and centers it inside `box_w`.
pub fn drawTextCentered(x: i32, y: i32, box_w: u32, text: []const u8, color: u32, atlas: *const Atlas) void {
    const tw = atlas.measure(text);
    const inset: i32 = if (box_w > tw) @intCast((box_w - tw) / 2) else 0;
    drawText(x + inset, y, text, color, atlas);
}

/// Per-pixel src-over blend onto `gfx.target`. Skips alpha=0 and fully
/// out-of-bounds pixels; alpha=255 takes a putpixel fast-path.
inline fn blendPx(x: i32, y: i32, color: u32, alpha: u8) void {
    if (alpha == 0) return;
    if (x < 0 or y < 0) return;
    const ux: u32 = @intCast(x);
    const uy: u32 = @intCast(y);
    if (ux >= gfx.target_w or uy >= gfx.target_h) return;
    const idx = uy * gfx.target_w + ux;
    if (alpha == 255) {
        gfx.target[idx] = color;
        return;
    }
    const dst = gfx.target[idx];
    const a: u32 = alpha;
    const inv: u32 = 255 - a;
    const sr = (color >> 16) & 0xFF;
    const sg = (color >> 8) & 0xFF;
    const sb = color & 0xFF;
    const dr = (dst >> 16) & 0xFF;
    const dg = (dst >> 8) & 0xFF;
    const db = dst & 0xFF;
    const r = (sr * a + dr * inv + 127) / 255;
    const g = (sg * a + dg * inv + 127) / 255;
    const b = (sb * a + db * inv + 127) / 255;
    gfx.target[idx] = (r << 16) | (g << 8) | b;
}
