// Source-line resolution for kernel addresses.
//
// Loads a pre-built KERNEL.LINE binary (generated by tools/gen_kernel_lines.py
// from objdump --dwarf=decodedline output) and exposes a single function:
// `lookup(addr) -> ?{file, line}`. The autopsy + backtrace use this to
// annotate every RIP with `at file.zig:NNN`, transforming
//
//   [3] cpu.syscall.sysMkdir+0xB4D (0xFFFFFFFF8025529D)
//
// into
//
//   [3] cpu.syscall.sysMkdir+0xB4D at syscall.zig:2371 (0xFFFFFFFF8025529D)
//
// which is far easier to triage than RIP+offset alone.
//
// Why this exists: kernel symbols only know `function+offset`. Mapping back
// to source line requires either a DWARF parser in-kernel (1000s of LoC,
// dynamic state machine) or pre-resolution at build time. We do the latter
// — pre-resolved entries are stable, compact (~16 bytes each), and lookup
// is a binary search.
//
// Memory cost: typical kernel = ~50k entries × 16B = 800 KB + ~50 KB file
// pool. Significant but bounded; freed if KERNEL.LINE is missing.

const serial = @import("serial.zig");
const debug = @import("debug.zig");
const heap = @import("../mm/heap.zig");
const vfs = @import("../fs/vfs.zig");
const paging = @import("../mm/paging.zig");

const LINE_MAGIC: u32 = 0x4C494E45; // "LINE"

pub const LineEntry = extern struct {
    addr: u64,
    file_off: u32,
    line: u32,
};

pub const LookupResult = struct {
    file: []const u8,
    line: u32,
};

const Table = struct {
    entries: [*]const LineEntry,
    count: u32,
    file_pool: [*]const u8,
    file_pool_len: u32,
};

var table: ?Table = null;

/// Load KERNEL.LINE from disk into kernel heap. Idempotent — silently
/// no-ops if already loaded or if the file is missing/malformed (any
/// failure path leaves table = null and the autopsy falls through to its
/// existing function+offset format).
pub fn init() void {
    if (table != null) return;

    const fresh = vfs.loadFileFresh("KERNEL.LINE") orelse {
        debug.klog("[dwarf-line] KERNEL.LINE not found on disk\n", .{});
        return;
    };
    const staging: [*]const u8 = fresh.buf;
    const file_size = fresh.size;
    defer {
        // vfs.loadFileFresh uses pmm.allocContiguous; pair with freeContiguous
        // for the correct API match. The per-frame freeFrame loop here was
        // mismatched and produced spurious [pmm-canary] mismatches on these
        // pages (freeFrame writes a canary per frame; freeContiguous skips
        // canary writes for bulk-freed contiguous ranges by design).
        const phys_base = paging.virtToPhys(@intFromPtr(fresh.buf)).?;
        @import("../mm/pmm.zig").freeContiguous(phys_base, fresh.pages);
    }

    if (file_size < 12) {
        debug.klog("[dwarf-line] KERNEL.LINE too small ({d} bytes)\n", .{file_size});
        return;
    }

    const header_ptr: [*]const u32 = @ptrCast(@alignCast(staging));
    const magic = header_ptr[0];
    const entry_count = header_ptr[1];
    const file_pool_size = header_ptr[2];

    if (magic != LINE_MAGIC) {
        debug.klog("[dwarf-line] Bad magic: 0x{X:0>8}\n", .{magic});
        return;
    }

    const entries_size = entry_count * @sizeOf(LineEntry);
    const expected_size = 12 + entries_size + file_pool_size;
    if (file_size < expected_size) {
        debug.klog("[dwarf-line] File too small: {d} < {d}\n", .{ file_size, expected_size });
        return;
    }

    const entries_buf = heap.kmallocAligned(entries_size, 8) orelse {
        debug.klog("[dwarf-line] Failed to allocate {d} bytes for entries\n", .{entries_size});
        return;
    };
    const src_entries = staging + 12;
    @memcpy(entries_buf[0..entries_size], src_entries[0..entries_size]);

    const pool_buf = heap.kmalloc(file_pool_size) orelse {
        heap.kfree(entries_buf);
        debug.klog("[dwarf-line] Failed to allocate {d} bytes for file pool\n", .{file_pool_size});
        return;
    };
    const src_pool = staging + 12 + entries_size;
    @memcpy(pool_buf[0..file_pool_size], src_pool[0..file_pool_size]);

    table = .{
        .entries = @ptrCast(@alignCast(entries_buf)),
        .count = entry_count,
        .file_pool = pool_buf,
        .file_pool_len = file_pool_size,
    };

    debug.klog("[dwarf-line] Loaded {d} line entries ({d} bytes file pool)\n", .{ entry_count, file_pool_size });
}

/// Resolve a kernel address to (file, line). Returns null if no DWARF
/// info is loaded or addr precedes every entry. Bounded "near" lookup:
/// returns the largest entry where entry.addr <= addr — in DWARF line
/// tables, each entry covers the address range up to the next entry, so
/// this is the canonical interpretation.
pub fn lookup(addr: u64) ?LookupResult {
    const t = table orelse return null;
    if (t.count == 0) return null;

    var lo: u32 = 0;
    var hi: u32 = t.count;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        if (t.entries[mid].addr <= addr) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    if (lo == 0) return null;
    const e = t.entries[lo - 1];

    // Sanity bound: if the next entry is more than 64 KB away (or this is
    // the last entry), the line entry probably doesn't actually cover
    // addr — better to return null than a misleading file:line.
    const range_end: u64 = if (lo < t.count) t.entries[lo].addr else e.addr + 0x10000;
    if (addr >= range_end) return null;

    if (e.file_off >= t.file_pool_len) return null;
    const name_start = t.file_pool + e.file_off;
    var name_len: u32 = 0;
    while (e.file_off + name_len < t.file_pool_len and name_start[name_len] != 0) {
        name_len += 1;
    }

    return .{
        .file = name_start[0..name_len],
        .line = e.line,
    };
}
