// Source-line resolution for kernel addresses.
//
// Loads a pre-built KERNEL.LINE binary (generated by tools/gen_kernel_lines.py
// from objdump --dwarf=decodedline output) and exposes a single function:
// `lookup(addr) -> ?{file, line}`. The autopsy + backtrace use this to
// annotate every RIP with `at file.zig:NNN`, transforming
//
//   [3] cpu.syscall.sysMkdir+0xB4D (0xFFFFFFFF8025529D)
//
// into
//
//   [3] cpu.syscall.sysMkdir+0xB4D at syscall.zig:2371 (0xFFFFFFFF8025529D)
//
// which is far easier to triage than RIP+offset alone.
//
// Why this exists: kernel symbols only know `function+offset`. Mapping back
// to source line requires either a DWARF parser in-kernel (1000s of LoC,
// dynamic state machine) or pre-resolution at build time. We do the latter
// — pre-resolved entries are stable, compact (8 bytes each, format in
// tools/gen_kernel_lines.py), and lookup is a binary search.
//
// Memory: the file stays where vfs.loadFileFresh read it (a PMM buffer kept
// for the whole uptime), not in the heap — ~250k entries = 2 MB.

const debug = @import("debug.zig");
const vfs = @import("../fs/vfs.zig");
const paging = @import("../mm/paging.zig");
const pmm = @import("../mm/pmm.zig");
const Phys = @import("../util/addr.zig").Phys;

const LINE_MAGIC: u32 = 0x324E494C; // "LIN2"

const Header = extern struct {
    magic: u32,
    count: u32,
    file_pool_len: u32,
    reserved: u32,
    addr_base: u64,
};

pub const LineEntry = extern struct {
    addr_off: u32,
    file_off: u16,
    line: u16,
};

comptime {
    if (@sizeOf(Header) != 24 or @sizeOf(LineEntry) != 8) @compileError("KERNEL.LINE layout drifted from tools/gen_kernel_lines.py");
}

pub const LookupResult = struct {
    file: []const u8,
    line: u32,
};

const Table = struct {
    entries: [*]const LineEntry,
    count: u32,
    addr_base: u64,
    file_pool: [*]const u8,
    file_pool_len: u32,
};

var table: ?Table = null;

/// Load KERNEL.LINE. Idempotent — silently no-ops if already loaded or if
/// the file is missing/malformed (any failure path leaves table = null and
/// the autopsy falls through to its existing function+offset format).
pub fn init() void {
    if (table != null) return;

    const fresh = vfs.loadFileFresh("KERNEL.LINE") orelse {
        debug.klog("[dwarf-line] KERNEL.LINE not found on disk\n", .{});
        return;
    };
    if (!adopt(fresh.buf, fresh.size)) {
        pmm.freeRange(Phys.of(paging.virtToPhys(@intFromPtr(fresh.buf)).?), fresh.pages);
        return;
    }
    const t = table.?;
    debug.klog("[dwarf-line] Loaded {d} line entries ({d} bytes file pool, {d} KB in place)\n", .{ t.count, t.file_pool_len, @as(usize, fresh.pages) * 4 });
}

/// Validate the file image and point `table` into it.
fn adopt(buf: [*]align(4) const u8, size: usize) bool {
    if (size < @sizeOf(Header)) {
        debug.klog("[dwarf-line] KERNEL.LINE too small ({d} bytes)\n", .{size});
        return false;
    }
    const h: *const Header = @ptrCast(@alignCast(buf));
    if (h.magic != LINE_MAGIC) {
        debug.klog("[dwarf-line] Bad magic: 0x{X:0>8} (want LIN2 — stale KERNEL.LINE?)\n", .{h.magic});
        return false;
    }
    const entries_size = @as(usize, h.count) * @sizeOf(LineEntry);
    const expected_size = @sizeOf(Header) + entries_size + h.file_pool_len;
    if (size < expected_size) {
        debug.klog("[dwarf-line] File too small: {d} < {d}\n", .{ size, expected_size });
        return false;
    }
    table = .{
        .entries = @ptrCast(@alignCast(buf + @sizeOf(Header))),
        .count = h.count,
        .addr_base = h.addr_base,
        .file_pool = buf + @sizeOf(Header) + entries_size,
        .file_pool_len = h.file_pool_len,
    };
    return true;
}

/// Resolve a kernel address to (file, line). Returns null if no DWARF
/// info is loaded or addr precedes every entry. Bounded "near" lookup:
/// returns the largest entry where entry.addr <= addr — in DWARF line
/// tables, each entry covers the address range up to the next entry, so
/// this is the canonical interpretation.
pub fn lookup(addr: u64) ?LookupResult {
    const t = table orelse return null;
    if (t.count == 0 or addr < t.addr_base) return null;
    const off = addr - t.addr_base;

    var lo: u32 = 0;
    var hi: u32 = t.count;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        if (t.entries[mid].addr_off <= off) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    if (lo == 0) return null;
    const e = t.entries[lo - 1];

    // Sanity bound: if the next entry is more than 64 KB away (or this is
    // the last entry), the line entry probably doesn't actually cover
    // addr — better to return null than a misleading file:line.
    const range_end: u64 = if (lo < t.count) t.entries[lo].addr_off else @as(u64, e.addr_off) + 0x10000;
    if (off >= range_end) return null;

    if (e.file_off >= t.file_pool_len) return null;
    const name_start = t.file_pool + e.file_off;
    var name_len: u32 = 0;
    while (e.file_off + name_len < t.file_pool_len and name_start[name_len] != 0) {
        name_len += 1;
    }

    return .{
        .file = name_start[0..name_len],
        .line = e.line,
    };
}
