#!/usr/bin/env python3
# Convert a BDF bitmap font into a Zig [256][H]uN array. Width/height are auto-
# detected from FONTBOUNDINGBOX and dictate the row type:
#   W <=  8 -> u8
#   W <= 16 -> u16
# Rows are MSB-justified into the chosen integer (leftmost pixel is the highest
# bit), matching how the existing drawChar16 / drawChar32 helpers iterate.
#
# Slots 0x20..0x7E carry ASCII directly. Slots 0x80..0x85 carry a hand-picked
# subset of Unicode block elements remapped from their U+25xx codepoints — see
# EXTRA_GLYPHS. This lets ASCII-art-style apps emit byte literals (e.g. "\x80")
# without needing UTF-8 decode in the terminal.
#
# Usage: python3 tools/bdf_to_zig.py <bdf-file> <out.zig> <font-name>

import sys

# Block element codepoints to extract from the BDF and the byte slots they live
# at in the generated atlas. Kept compact (6 entries) so the atlas stays small.
EXTRA_GLYPHS = {
    0x2588: (0x80, "FULL BLOCK"),       # █
    0x2591: (0x81, "LIGHT SHADE"),      # ░
    0x2592: (0x82, "MEDIUM SHADE"),     # ▒
    0x2593: (0x83, "DARK SHADE"),       # ▓
    0x2580: (0x84, "UPPER HALF BLOCK"), # ▀
    0x2584: (0x85, "LOWER HALF BLOCK"), # ▄
}


def parse_bdf(path):
    glyphs = {}
    with open(path, "r", encoding="latin-1") as f:
        lines = list(f.readlines())

    encoding = None
    in_bitmap = False
    rows = []
    bbx = None
    font_bbx = None

    for line in lines:
        line = line.rstrip("\r\n")
        if line.startswith("FONTBOUNDINGBOX"):
            parts = line.split()
            font_bbx = (int(parts[1]), int(parts[2]), int(parts[3]), int(parts[4]))
        elif line.startswith("ENCODING"):
            encoding = int(line.split()[1])
        elif line.startswith("BBX"):
            parts = line.split()
            bbx = (int(parts[1]), int(parts[2]), int(parts[3]), int(parts[4]))
        elif line.strip() == "BITMAP":
            in_bitmap = True
            rows = []
        elif line.strip() == "ENDCHAR":
            if encoding is not None and bbx is not None and (
                0 <= encoding < 128 or encoding in EXTRA_GLYPHS
            ):
                glyphs[encoding] = (bbx, rows)
            encoding = None
            bbx = None
            rows = []
            in_bitmap = False
        elif in_bitmap:
            rows.append(line.strip())

    if font_bbx is None:
        raise SystemExit("BDF missing FONTBOUNDINGBOX")
    return font_bbx, glyphs


def render_glyph(font_bbx, bbx, rows, row_bytes, total_bits):
    """Render one glyph into a list of `fh` integers, each holding `total_bits`
    of pixel data MSB-justified (top bit = leftmost pixel)."""
    fw, fh, _fxoff, fyoff = font_bbx
    bw, bh, bxoff, byoff = bbx

    out = [0] * fh
    top_in_canvas = (fh + fyoff) - (bh + byoff)
    full_mask = (1 << total_bits) - 1

    for i, row_hex in enumerate(rows[:bh]):
        if not row_hex:
            continue
        # BDF zero-pads each row to row_bytes bytes; bytes are big-endian, so
        # the leftmost pixel is the MSB of the first byte. Pad/truncate as needed.
        hex_str = row_hex.ljust(row_bytes * 2, "0")[: row_bytes * 2]
        raw = int(hex_str, 16)
        # `raw` has ceil(W/8)*8 bits; the rightmost (8 - W%8)%8 bits are padding.
        # Right-align to total_bits = fw, then keep MSB-justified by shifting up
        # to the chosen storage width's MSB later in emit_zig.
        pad_bits = row_bytes * 8 - fw
        if pad_bits > 0:
            raw >>= pad_bits  # drop padding so top fw bits hold pixels 0..fw-1
        # Apply per-glyph x offset (positive shifts right within glyph's W bits).
        if bxoff > 0:
            raw >>= bxoff
        elif bxoff < 0:
            raw = (raw << (-bxoff)) & full_mask
        canvas_y = top_in_canvas + i
        if 0 <= canvas_y < fh:
            out[canvas_y] |= raw & full_mask

    return out


def storage_bits_for(width):
    if width <= 8:
        return 8
    if width <= 16:
        return 16
    raise SystemExit(f"Unsupported width {width}; only u8/u16 row storage handled")


def emit_zig(font_name, font_bbx, glyphs, out_path):
    fw, fh, _, _ = font_bbx
    storage_bits = storage_bits_for(fw)
    storage_type = f"u{storage_bits}"
    # Shift pixel bits up so the leftmost pixel sits in the storage MSB. drawChar
    # then reads with `(0x80 >> col)` for u8 or `(0x8000 >> col)` for u16.
    msb_shift = storage_bits - fw
    hex_width = storage_bits // 4

    lines = []
    lines.append(f"// {fw}x{fh} bitmap font — {font_name}")
    lines.append("// Auto-generated by tools/bdf_to_zig.py — DO NOT EDIT BY HAND")
    lines.append(
        f"// Each character is {fh} rows of {storage_type}: top {fw} bits are pixels, MSB = leftmost."
    )
    lines.append("// Indexed by byte value 0x00..0xFF. ASCII at its native code; selected")
    lines.append("// Unicode block elements remapped to 0x80..0x85 (see EXTRA_GLYPHS in the")
    lines.append("// generator). All other slots are zeroed.")
    lines.append("")
    lines.append(f"pub const char_w: u32 = {fw};")
    lines.append(f"pub const char_h: u32 = {fh};")
    lines.append(f"pub const advance: u32 = {fw + 1}; // {fw}px + 1px spacing")
    lines.append("")
    lines.append(f"pub const data: [256][{fh}]{storage_type} = init: {{")
    lines.append(
        f"    var d: [256][{fh}]{storage_type} = "
        f"[_][{fh}]{storage_type}{{[_]{storage_type}{{0}} ** {fh}}} ** 256;"
    )
    lines.append("")

    # ASCII glyphs at their native byte values.
    for cp in sorted(glyphs):
        if not (0x20 <= cp <= 0x7E):
            continue
        rendered = glyphs[cp]
        full_mask = (1 << storage_bits) - 1
        shifted = [(v << msb_shift) & full_mask for v in rendered]
        bytes_str = ", ".join(f"0x{b:0{hex_width}X}" for b in shifted)
        ch = chr(cp)
        display = ch if ch not in ("'", "\\") else "\\" + ch
        lines.append(f"    d[0x{cp:02X}] = .{{ {bytes_str} }}; // '{display}'")

    # Block elements remapped to the 0x80..0x85 range (the byte slot is what
    # callers index by; the comment shows the source codepoint).
    lines.append("")
    lines.append("    // --- Unicode block elements (remapped from U+25xx) ---")
    for cp, (slot, name) in sorted(EXTRA_GLYPHS.items(), key=lambda x: x[1][0]):
        if cp not in glyphs:
            lines.append(f"    // (skipped) 0x{slot:02X} <- U+{cp:04X} {name}: not present in BDF")
            continue
        rendered = glyphs[cp]
        full_mask = (1 << storage_bits) - 1
        shifted = [(v << msb_shift) & full_mask for v in rendered]
        bytes_str = ", ".join(f"0x{b:0{hex_width}X}" for b in shifted)
        lines.append(f"    d[0x{slot:02X}] = .{{ {bytes_str} }}; // U+{cp:04X} {name}")

    lines.append("")
    lines.append("    break :init d;")
    lines.append("};")
    lines.append("")

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))


def main():
    if len(sys.argv) != 4:
        print("Usage: bdf_to_zig.py <bdf-file> <out.zig> <font-name>", file=sys.stderr)
        sys.exit(1)
    bdf_path, out_path, font_name = sys.argv[1], sys.argv[2], sys.argv[3]

    font_bbx, raw_glyphs = parse_bdf(bdf_path)
    fw, fh, _, _ = font_bbx
    storage_bits = storage_bits_for(fw)
    row_bytes = (fw + 7) // 8

    rendered = {}
    for cp, (bbx, rows) in raw_glyphs.items():
        rendered[cp] = render_glyph(font_bbx, bbx, rows, row_bytes, fw)

    emit_zig(font_name, font_bbx, rendered, out_path)
    ascii_count = sum(1 for cp in rendered if 0x20 <= cp <= 0x7E)
    extra_count = sum(1 for cp in rendered if cp in EXTRA_GLYPHS)
    print(
        f"[bdf->zig] {ascii_count} ASCII + {extra_count} block-element glyphs "
        f"({fw}x{fh}, u{storage_bits}) from {bdf_path} -> {out_path}"
    )


if __name__ == "__main__":
    main()
